driver:
  name: vagrant
  gui: true
  provider: virtualbox
  linked_clone: true

driver_config:
  guest: windows
  communicator: 'winrm'

provisioner:
  name: chef_zero
  # deprecations_as_errors: true

verifier:
  name: inspec
  format: documentation

platforms:
  - name: windows2012r2-windowsonly

suites:
  - name: default
    run_list:
      - recipe[windows_hardening::default]

  - name: production
    run_list:
      - recipe[windows_hardening::deleteautologon]
      - recipe[joindomain::default]
      - recipe[windows_hardening::domainjoined]
      - recipe[windows_hardening::default]
    verifier:
      inspec_tests:
        - test/integration/default/core_hardening_spec.rb
