name 'windows_hardening'
maintainer 'Matt Tunny'
maintainer_email 'matt.tunny@gmail.com'
license 'all_rights'
description 'windows_hardening'
long_description 'windows_hardening'
source_url 'https://github.com/MattTunny/windows_hardening'
issues_url 'https://github.com/MattTunny/windows_hardeningissues'
version '0.1.0'

depends 'windows'
